# Generated by Django 5.0.2 on 2024-05-29 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
        ('calculation_of_services', '0002_personalaccount'),
        ('users', '0002_rename_photo_user_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='calculation_of_services.personalaccount', verbose_name='Лицевой счет'),
        ),
        migrations.AlterField(
            model_name='user',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='building.flat', verbose_name='Квартира'),
        ),
    ]
