# Generated by Django 5.0.2 on 2024-05-28 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('background_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Многоквартирный дом',
                'verbose_name_plural': 'Многоквартирные дома',
            },
        ),
        migrations.CreateModel(
            name='MeterDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Прибор учета',
                'verbose_name_plural': 'Приборы учета',
            },
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=25)),
                ('apartment_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrance', to='building.apartmentblock')),
            ],
            options={
                'verbose_name': 'Подъезд',
                'verbose_name_plural': 'Подъезды',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=25)),
                ('area_of_apartments', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('entrance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flat', to='building.entrance')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='private_person', to='background_information.privateperson')),
            ],
            options={
                'verbose_name': 'Квартиру',
                'verbose_name_plural': 'Квартираы',
            },
        ),
    ]
