# Generated by Django 5.0.2 on 2024-12-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'Квартиру', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.RemoveField(
            model_name='apartmentblock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entrance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='meterdevice',
            name='name',
        ),
        migrations.AddField(
            model_name='apartmentblock',
            name='address',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='apartmentblock',
            name='city',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='apartmentblock',
            name='region',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='apartmentblock',
            name='street',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='commissioning_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию'),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='date_of_sealing',
            field=models.DateField(blank=True, null=True, verbose_name='Дата опломбирования'),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='decommissioning_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата вывода из эксплуатации'),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='electricity',
            field=models.BooleanField(default=False, verbose_name='Учет электроэнергии'),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='factory_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Заводской (серийный) номер'),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='meter_device', to='building.flat'),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='id_gis',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Идентификатор ЖКУ'),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата установки'),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='is_installed',
            field=models.BooleanField(default=False, verbose_name='Установлен'),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='number_of_tariffs',
            field=models.IntegerField(default=0, verbose_name='Количество тарифов'),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='remote_reading',
            field=models.BooleanField(default=False, verbose_name='Дистанционного снятия показаний'),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Модел'),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='type_device',
            field=models.IntegerField(
                choices=[(0, 'тип прибора не определён'), (1, 'Холодная вода'), (2, 'Горячая вода'),
                         (3, 'Электроэнергия'), (4, 'Электроэнергия день'), (5, 'Электроэнергия ночь')], default=0,
                verbose_name='Тип прибора учета'),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='verification_interval',
            field=models.IntegerField(default=0, verbose_name='Межповерочный интервал'),
        ),
    ]
