# Generated by Django 5.0.2 on 2024-12-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_alter_flat_options_remove_apartmentblock_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'ordering': ['id'], 'verbose_name': 'Квартиру', 'verbose_name_plural': 'Квартиры'},
        ),
    ]
