# Generated by Django 5.0.2 on 2024-05-28 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('background_information', '0001_initial'),
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата ввода')),
                ('value', models.DecimalField(decimal_places=5, max_digits=20, verbose_name='Показания')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='building.flat', unique_for_date='date', verbose_name='Квартира')),
                ('meter_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='building.meterdevice', unique_for_date='date', verbose_name='Прибор учета')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='background_information.utilityservice', unique_for_date='date', verbose_name='Комунальная услуга')),
            ],
            options={
                'verbose_name': 'Показания прибора учета',
                'verbose_name_plural': 'Показания приборов учета',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Начало действия')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Тариф')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='background_information.utilityservice', verbose_name='Комунальная услуга')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
    ]
