# Generated by Django 5.0.2 on 2024-05-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_of_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Лицевой счет',
                'verbose_name_plural': 'Лицевые счета',
            },
        ),
    ]
