# Generated by Django 5.0.2 on 2024-05-28 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivatePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, verbose_name='Наименование')),
                ('firstname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('lastname', models.CharField(max_length=255, verbose_name='Имя')),
                ('middlename', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
            },
        ),
        migrations.CreateModel(
            name='UnitsOfMeasures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Наименование')),
                ('fullname', models.CharField(blank=True, max_length=255, verbose_name='Полное наименование')),
                ('code', models.CharField(blank=True, max_length=4, verbose_name='Код ед. измерения')),
            ],
            options={
                'verbose_name': 'Единицы измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='UtilityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantify', models.IntegerField(choices=[(0, 'по умолчанию 1'), (1, 'полщадь квартиры'), (2, 'количество людей'), (3, 'по прибору')], default=0, verbose_name='Количество для расчета')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='background_information.unitsofmeasures', verbose_name='Ед. имерения')),
            ],
            options={
                'verbose_name': 'Коммунальная услуга',
                'verbose_name_plural': 'Коммунальные услуги',
            },
        ),
    ]
